"""booktrack_id pour dedup import Book Track

Revision ID: 1d5d73910b32
Revises: ff98b093454f
Create Date: 2026-08-16 08:29:04.156216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  — types AutoString utilisés par l'autogenerate


# revision identifiers, used by Alembic.
revision: str = '1d5d73910b32'
down_revision: Union[str, Sequence[str], None] = 'ff98b093454f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('booktrack_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    # Dédup de l'import Book Track garantie au niveau base : deux livres ne
    # peuvent pas partager le même UUID Book Track. SQLite n'applique pas
    # l'unicité aux NULL — les livres hors import ne sont pas affectés.
    op.create_index('uq_book_booktrack_id', 'book', ['booktrack_id'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('uq_book_booktrack_id', table_name='book')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'booktrack_id')
    # ### end Alembic commands ###
