"""initial schema (SPEC.md s2)

Revision ID: 36ce8285e200
Revises: 
Create Date: 2026-08-14 19:33:14.406471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ce8285e200'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('openlibrary_key', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sqlite_autoincrement=True
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('isbn10', sa.Text(), nullable=True),
    sa.Column('isbn13', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('published_date', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_path', sa.Text(), nullable=True),
    sa.Column('cover_source', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'tbr'"), nullable=False),
    sa.Column('owned', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('current_page', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('current_percent', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('acquired_date', sa.Text(), nullable=True),
    sa.Column('openlibrary_work', sa.Text(), nullable=True),
    sa.Column('openlibrary_edition', sa.Text(), nullable=True),
    sa.Column('google_books_id', sa.Text(), nullable=True),
    sa.Column('koreader_md5', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_book_koreader_md5', 'book', ['koreader_md5'], unique=False)
    op.create_index('idx_book_status', 'book', ['status'], unique=False)
    op.create_table('koreader_import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_sha256', sa.Text(), nullable=False),
    sa.Column('imported_at', sa.Text(), nullable=False),
    sa.Column('sessions_added', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('books_matched', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('books_unmatched', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), server_default=sa.text("'tag'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'kind'),
    sqlite_autoincrement=True
    )
    op.create_table('book_author',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    op.create_table('book_label',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'label_id')
    )
    op.create_table('highlight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('chapter', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('highlighted_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_highlight_book', 'highlight', ['book_id'], unique=False)
    op.create_table('read_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('reading_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=False),
    sa.Column('ended_at', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('end_page', sa.Integer(), nullable=True),
    sa.Column('pages_read', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('koreader_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_session_book', 'reading_session', ['book_id'], unique=False)
    op.create_index('idx_session_started', 'reading_session', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_session_started', table_name='reading_session')
    op.drop_index('idx_session_book', table_name='reading_session')
    op.drop_table('reading_session')
    op.drop_table('read_entry')
    op.drop_index('idx_highlight_book', table_name='highlight')
    op.drop_table('highlight')
    op.drop_table('book_label')
    op.drop_table('book_author')
    op.drop_table('label')
    op.drop_table('koreader_import')
    op.drop_index('idx_book_status', table_name='book')
    op.drop_index('idx_book_koreader_md5', table_name='book')
    op.drop_table('book')
    op.drop_table('author')
    # ### end Alembic commands ###
